### ISSUE TITLE
Sotp working in vs code 1.44.1 version

### ISSUE THREAD

**Issue by MaazCW** [dsebastien/vscode-extension-packs#1]
Issue Type: <b>Bug</b>

Sotp working in vs code 1.44.1 version

Extension version: 1.4.0
VS Code version: Code 1.44.1 (a9f8623ec050e5f0b44cc8ce8204a1455884749f, 2020-04-11T01:48:12.622Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (6.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by dsebastien** [comment]
Hello Maaz. Can you tell me what stopped working with that version?

**Comment by dsebastien** [comment]
Not updated in a while; please reopen if you still have issues but in that case provide me with some more information :)
